# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4646dd632a674481181fdaa5e85394537d4e619c8b41b314b9439439814fbaf887456101896550d4ce396389efa967c40707784dc4ae650b4c35fb67f983218

test:
  secret_key_base: 8386b3316eea920f2b9ab8c315aabdc20138fc6bad0f804bec21a2cff594d261b26efa8280b5f4951cd83c51f6b09452f64251d0f9d52849fe091370ae65e731

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
